### ISSUE TITLE
[suggestion] Low contrast in comments

### ISSUE THREAD

**Issue by rodrigojcmello** [coeiico/jetbrains-nightfall-theme#3]
First of all, congratulations on the great theme.

Currently I have been working a lot with accessibility to the Web and the comment caught my attention a lot, his contrast is low even for me, I have no visual impairment and I have difficulty reading the comments

The contrast is 1.31 which is really very low. I added 10 lighness (hsl) to the color of the comment and the contrast has already gone to almost 2, which is still not the ideal, but it already improves the reading a lot. A contrast 3 (which is the minimum recommended for accessibility) would be almost white, and so I think it would run away from the gray idea for comments.

<img width="682" alt="Captura de Tela 2021-03-06 às 09 56 04" src="https://user-images.githubusercontent.com/5174526/110207661-db280200-7e39-11eb-9e8a-0bf7ffbfef26.png">
<img width="773" alt="Captura de Tela 2021-03-06 às 10 09 18" src="https://user-images.githubusercontent.com/5174526/110207702-1fb39d80-7e3a-11eb-8ab9-134d2d9d1c55.png">

<img width="744" alt="Captura de Tela 2021-03-06 às 09 59 21" src="https://user-images.githubusercontent.com/5174526/110207757-83d66180-7e3a-11eb-9fe3-12b06dc2cbbb.png">

**Comment by coeiico** [comment]
Thank you!

Yea I agree, I tried to go with a style that would blend the comments in with the background more so that they seemed more out of the way. But I've noticed on some screens with different color profiles they seem much darker, and on macbook retina displays it's difficult to read what was written. 

I've updated the color of the comments to be a little brighter, which should be available in the next update 👍 

Edit:
The new color will closely resemble the new color that you proposed.

**Comment by coeiico** [comment]
@all-contributors add @rodrigojcmello for ideas

**Comment by karlmiles** [comment]
It's definitely much more readable for me. on my machine.  This is PhpStorm 2021.1 EAP on Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/2984054/110517467-cfbb2c00-8102-11eb-9e90-c526e5b66388.png)

There's nothing special about it being on the EAP - it's the same for me in stable versions and other IDEs.  Ignore the background colouration on `return` -  that's the Return Highlighter plugin.  Should also say, I override the font as it's far too small on my machine.  The screenshot is using JetBrainsMonoMedium Nerd Font, 14 with ligatures enabled.

**Comment by karlmiles** [comment]
Okay, so I've disabled my font override just as an experiment (and re-enabled Indent Rainbow & Rainbow brackets because I was going to do some stuff!), and the contrast is so much lower now:

![image](https://user-images.githubusercontent.com/2984054/110520663-b0260280-8106-11eb-8b02-732efac63d65.png)

This isn't resized, it's how it renders on my laptop, hence why I bump it up to 14 from 8 - I'd probably go to 11 or 12 usually but, the ligature for === isn't pretty and it's somewhat distracting when the lines aren't equally spaced)

**Comment by karlmiles** [comment]
Apologies.  I think the difference is down to me tweaking things over previous weeks, and my settings are sync'd to my account.  Which means, even after resetting the colour scheme back to your stock values, that settings sync kicks in and clobbers it!

**Comment by coeiico** [comment]
I've been experimenting and came across some colors that I think fits well with the theme, the new comment and line colors for v1.1.0 look great and are definitly more visible 👍

**Comment by karlmiles** [comment]
I don't know what's going on with the comment colours on my machines.  I'd disabled config sync, deleted any duplicated colour schemes, reset this one back, disabled plugins that do anything with colour, and still, the comment text is dark to begin with and then goes far lighter after a restart.  I've even deleted the files on disk too with the IDE shutdown.  What's strange is, even with a reset, the hex codes for block & line, doc comment > text, are all set to #ABB2BF and that's pretty bright - and matches with those earlier screen shots.

I'll uninstall the theme and pull in 1.1.0. :crossed_fingers:

**Comment by karlmiles** [comment]
:tada: The issue seems to have resolved itself.  1.1.0 looks pretty nice!  I don't know if my 1.0.9 install was faulty and I've jumped a few iterations as a result, or 1.1.0 has a lot of tweaks to it but, it's instantly noticeable.  I'm liking the new changes!

**Comment by coeiico** [comment]
Yup there were a lot of issues caused by transparent colors, which produced inconsistent colors on different screens, and I've done a lot of tweaks for 1.1.0, hopefully they look great 🙂
